### PR TITLE
Wrap console.error calls in debug mode checks

### PR DESCRIPTION
**Pull request by Seikho**
Aims to address #28

### CODE REVIEW

**Comment by coolaj86** [comment]
Hey @Seikho, I'm adding you to the repo. feel free to merge in the changes, test them, and let me know that it's okay to publish.

There are a number of fairly simple changes that I just haven't had time to manage, feel free to do so. Also, I won't be offended if you decide remove yourself from the repo(s).

Thanks for your help.

**Comment by Seikho** [comment]
Thanks, @coolaj86. Hope ya don't mind, but this opens a few more questions. I can create issues and PRs for these pretty much immediately. Namely fixing up the README (re: `le.middleware()`) and adding type definitions for TypeScript users.

I gave logging a bit more thought. This PR implements a bit of a funny truth table for logging, so I'll go about fixing that and implement a more DRY approach to logging.

**Comment by coolaj86** [comment]
Hey, feel free to fix the readme and adding type defs and DRYing things up. I'm finally back into working on these repos for a few days to get some issues knocked out.

**Comment by coolaj86** [comment]
Logging is now properly wrapped.

Version 2.x is now available: https://github.com/Daplie/node-letsencrypt

**Pull request closed without merging**
